### ISSUE TITLE
Handle invalid data from BPUP

### ISSUE THREAD

**Issue by bdraco** [prystupa/bond-api#14]
```
2021-11-30 17:24:55 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1029, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.9/site-packages/bond_api/bpup.py", line 83, in datagram_received
    self.bpup_subscriptions.notify(json.loads(data.decode()[:-1]))
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 71 (char 70)
```

**Comment by bdraco** [comment]
Enabled debug logging.  Hopefully I can catch the corrupted json message happening again

**Comment by bdraco** [comment]
Looks like its

```
2021-12-07 07:18:57 DEBUG (MainThread) [bond_api.bpup] BPUP message: b'{"B":"KVPRBDG89315","_error_id":633,"_error_msg":"BPUP client timeout"}'
2021-12-07 07:18:57 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1029, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.9/site-packages/bond_api/bpup.py", line 83, in datagram_received
    self.bpup_subscriptions.notify(json.loads(data.decode()[:-1]))
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 71 (char 70)
```

**Comment by bdraco** [comment]
`{"B":"KVPRBDG89315","_error_id":633,"_error_msg":"BPUP client timeout"}`

**Comment by bdraco** [comment]
All the other messages are newline terminated
`b'{"B":"KVPRBDG89415","d":0,"v":"v2.29.2-beta"}\n'`

**Comment by bdraco** [comment]
The api example is `{"B":"ZZBL12345","err_id":631,"err_msg":"BPUP client timeout"}\n`

It looks like we need to strip newlines and be ok with them not being there

`err_id` or `_err_id`
`err_msg` or `_err_msg`
